EXTERNAL CurrentSpeaker(timing, actorName)
EXTERNAL SetPortrait(timing, actorName, portrait)
EXTERNAL SetFacingDirection(timing, actorName, direction, withBounce)
EXTERNAL PlaySound(timing, soundName)
EXTERNAL PlayMusic(timing, musicName)
EXTERNAL EditFontSize(timing, fontSize, speakerOrDialogue)
EXTERNAL PlaceActor(timng, actorName, position)
EXTERNAL MoveActor(timing, actorname, destination, timeToComplete)
EXTERNAL RemoveActor(timing, actorName)
EXTERNAL FadeActor(timing, actorName, timeToComplete)